---
builds:
  - binary: masonry
    main: ./cmd/masonry/masonry.go
    ldflags: -s -w -X github.com/opencontrol/compliance-masonry/version.Version={{.Version}} -X github.com/opencontrol/compliance-masonry/version.Commit={{.Commit}} -X github.com/opencontrol/compliance-masonry/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

  - binary: compliance-masonry
    main: ./cmd/compliance-masonry/compliance-masonry.go
    ldflags: -s -w -X github.com/opencontrol/compliance-masonry/version.Version={{.Version}} -X github.com/opencontrol/compliance-masonry/version.Commit={{.Commit}} -X github.com/opencontrol/compliance-masonry/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - 386

archives:
  - files:
      - LICENSE.md
      - README.md
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - vendor: OpenControl
    homepage: https://github.com/opencontrol/compliance-masonry
    license: CC0 1.0
    maintainer: OpenControl Developers <dev@open-control.org>
    formats:
      - deb
      - rpm

brews:
  - name: compliance-masonry
    tap:
      owner: opencontrol
      name: homebrew-compliance-masonry
    commit_author:
      name: OpenControl
      email: dev@open-control.org
    description: Compliance Masonry is a command-line interface (CLI) that allows users to construct certification documentation using the OpenControl Schema.
    homepage: https://github.com/opencontrol/compliance-masonry
    install: bin.install "compliance-masonry", "masonry"
