builds:
  - binary: compliance-masonry
    main: ./masonry-go.go ./diff.go
    ldflags: -s -w -X github.com/opencontrol/compliance-masonry/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64

nfpm:
  homepage: https://github.com/opencontrol/compliance-masonry
  license: CC0 1.0
  formats:
    - deb
    - rpm

brew:
  name: oscalkit
  github:
    owner: opencontrol
    name: homebrew-oscalkit
  commit_author:
    name: OpenControl
    email: dev@open-control.org
  homepage: https://github.com/opencontrol/compliance-masonry
