version: 2
jobs:
  build:
    working_directory: /go/src/github.com/opencontrol/compliance-masonry
    docker:
      - image: docker:17-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and run test container
          command: make test
      - run:
          name: Send results to Codecov
          command: bash <(curl -s https://codecov.io/bash)
