version: 2
jobs:
  build:
    working_directory: /go/src/github.com/opencontrol/compliance-masonry
    docker:
      - image: golang:1.8-alpine
    steps:
      - run:
          name: Install Git
          command: apk add bash git
      - checkout

      - run:
          name: Build the program
          command: go build

      - run:
          name: Download test dependencies
          command: |
            go get \
              github.com/axw/gocov/gocov \
              github.com/Masterminds/glide \
              github.com/mattn/goveralls \
              golang.org/x/tools/cmd/cover
      - run:
          name: Run tests
          command: ./circleci/coverage.sh
