author:
  name: Cloud.gov | 18F
  url: https://cloud.18f.gov/
defaults:
- scope:
    path: ''
  values:
    layout: guides_style_18f_default
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
google_analytics_ua: null
highlighter: rouge
logoalt: 18F logo
logourl: /assets/img/18f-logo.png
markdown: redcarpet
name: Control Masonry
navigation:
- internal: true
  text: Introduction
  url: index.html
- children:
  - internal: true
    text: AC-2 Account Management
    url: AC-2/
  - internal: true
    text: AC-2 (1) Account Management | Automated System Account Management
    url: AC-2 (1)/
  - internal: true
    text: AC-2 (2) Account Management | Removal of Temporary / Emergency Accounts
    url: AC-2 (2)/
  - internal: true
    text: AC-2 (3) Account Management | Disable Inactive Accounts
    url: AC-2 (3)/
  - internal: true
    text: AC-2 (4) Account Management | Automated Audit Actions
    url: AC-2 (4)/
  - internal: true
    text: AC-2 (5) Account Management | Inactivity Logout
    url: AC-2 (5)/
  - internal: true
    text: AC-2 (7) Account Management | Role-Based Schemes
    url: AC-2 (7)/
  - internal: true
    text: AC-2 (9) Account Management | Restrictions on Use of Shared Groups / Accounts
    url: AC-2 (9)/
  - internal: true
    text: AC-2 (10) Account Management | Shared / Group Account Credential Termination
    url: AC-2 (10)/
  - internal: true
    text: AC-2 (12) Account Management | Account Monitoring / Atypical Usage
    url: AC-2 (12)/
  - internal: true
    text: AC-3 Access Enforcement
    url: AC-3/
  - internal: true
    text: AC-6 Least Privilege
    url: AC-6/
  - internal: true
    text: AC-6 (1) Least Privilege | Authorize Access to Security Functions
    url: AC-6 (1)/
  - internal: true
    text: AC-6 (2) Least Privilege | Non-Privileged Access For No security Functions
    url: AC-6 (2)/
  - internal: true
    text: AC-6 (5) Least Privilege | Privileged Accounts
    url: AC-6 (5)/
  - internal: true
    text: AC-6 (9) Least Privilege | Auditing Use of Privileged Functions
    url: AC-6 (9)/
  - internal: true
    text: AC-6 (10) Least Privilege | Prohibit Non-privileged Users from Executing
      Privileged Functions
    url: AC-6 (10)/
  - internal: true
    text: AU-2 Audit Events
    url: AU-2/
  - internal: true
    text: AU-2 (3) Audit Events | Reviews and Updates
    url: AU-2 (3)/
  - internal: true
    text: AU-6 Audit Review, Analysis, and Reporting
    url: AU-6/
  - internal: true
    text: AU-6 (1) Audit Review, Analysis, and Reporting | Process Integration
    url: AU-6 (1)/
  - internal: true
    text: AU-6 (3) Audit Review, Analysis, and Reporting | Correlate Audit Repositories
    url: AU-6 (3)/
  - internal: true
    text: CA-8 Penetration Testing
    url: CA-8/
  - internal: true
    text: CA-8 (1) Penetration Testing | Independent Penetration Agent or Team
    url: CA-8 (1)/
  - internal: true
    text: CM-2 (1) Baseline Configuration | Reviews and Updates
    url: CM-2 (1)/
  - internal: true
    text: CM-2 (3) Baseline Configuration | Retention of Previous Configurations
    url: CM-2 (3)/
  - internal: true
    text: CM-2 (7) Baseline Configuration | Configure Systems, Components, or Devices
      for High-Risk Areas
    url: CM-2 (7)/
  - internal: true
    text: CM-2(2) Baseline Configuration | Automation Support For Accuracy / Currency
    url: CM-2(2)/
  - internal: true
    text: CM-3 Configuration Change Control
    url: CM-3/
  - internal: true
    text: CM-6 Configuration Settings
    url: CM-6/
  - internal: true
    text: CM-6 (1) Configuration Settings | Automated essential Management / Application
      / Verification
    url: CM-6 (1)/
  - internal: true
    text: CM-8 Information System Component Inventory
    url: CM-8/
  - internal: true
    text: CM-8 (1) Information System Component Inventory | Updates During Installations
      / Removals
    url: CM-8 (1)/
  - internal: true
    text: CM-8 (3) Information System Component Inventory | Automated Unauthorized
      Component Detection
    url: CM-8 (3)/
  - internal: true
    text: CM-8 (5) Information System Component Inventory | No Duplicate Accounting
      of Components
    url: CM-8 (5)/
  - internal: true
    text: IA-2 (1) Identification and Authentication (Organizational Users) | Network
      Access to Privileged Accounts
    url: IA-2 (1)/
  - internal: true
    text: IA-2 (2) Identification and Authentication (Organizational Users) | Network
      Access to Non-Privileged Accounts
    url: IA-2 (2)/
  - internal: true
    text: IA-2 (12) Identification and Authentication (Organizational Users) | Acceptance
      of PIV Credentials
    url: IA-2 (12)/
  - internal: true
    text: PL-8 Information Security Architecture
    url: PL-8/
  - internal: true
    text: RA-5 Vulnerability Scanning
    url: RA-5/
  - internal: true
    text: RA-5 (1) Vulnerability Scanning | Update Tool Capability
    url: RA-5 (1)/
  - internal: true
    text: RA-5 (2) Vulnerability Scanning | Update by Frequency / Prior to New Scan
      / When Identified
    url: RA-5 (2)/
  - internal: true
    text: RA-5 (3) Vulnerability Scanning | Breadth / Depth of Coverage
    url: RA-5 (3)/
  - internal: true
    text: RA-5 (5) Vulnerability Scanning | Privileged Access
    url: RA-5 (5)/
  - internal: true
    text: RA-5 (6) Vulnerability Scanning | Automated Trend Analyses
    url: RA-5 (6)/
  - internal: true
    text: RA-5 (8) Vulnerability Scanning | Review Historic Audit Logs
    url: RA-5 (8)/
  - internal: true
    text: SA-11 (1) Developer Security Testing and Evaluation | Static Code Analysis
    url: SA-11 (1)/
  - internal: true
    text: SC-7 Boundary Protection
    url: SC-7/
  - internal: true
    text: SC-7 (3) Boundary Protection | Access Points
    url: SC-7 (3)/
  - internal: true
    text: SC-7 (5) Boundary Protection | Deny by Default / Allow by Exception
    url: SC-7 (5)/
  - internal: true
    text: SC-7 (12) Boundary Protection | Host-Based Protection
    url: SC-7 (12)/
  - internal: true
    text: SC-7 (13) Boundary Protection | Isolation of Security Tools / Mechanisms
      / Support Components
    url: SC-7 (13)/
  - internal: true
    text: SC-13 Cryptographic Protection
    url: SC-13/
  - internal: true
    text: SC-28 (1) Protection Of Information At Rest | Cryptographic Protection
    url: SC-28 (1)/
  - internal: true
    text: SI-2 Flaw Remediation
    url: SI-2/
  - internal: true
    text: SI-2 (2) Flaw Remediation | Automated Flaw Remediation Status
    url: SI-2 (2)/
  - internal: true
    text: SI-2 (3) Flaw Remediation | Time to Remediate Flaws / Benchmarks for Corrective
      Actions
    url: SI-2 (3)/
  - internal: true
    text: SI-4 Information System Monitoring
    url: SI-4/
  - internal: true
    text: SI-4 (1) Information System Monitoring | System-Wide Intrusion Detection
      System
    url: SI-4 (1)/
  - internal: true
    text: SI-4 (2) Information System Monitoring | Automated Tools For Real-Time Analysis
    url: SI-4 (2)/
  - internal: true
    text: SI-4 (4) Information System Monitoring | Inbound and Outbound Communications
      Traffic
    url: SI-4 (4)/
  - internal: true
    text: SI-4 (5) Information System Monitoring | System-Generated Alerts
    url: SI-4 (5)/
  - internal: true
    text: SI-4 (16) Information System Monitoring | Correlate Monitoring Information
    url: SI-4 (16)/
  - internal: true
    text: SI-4 (23) Information System Monitoring | Host-Based Devices
    url: SI-4 (23)/
  - internal: true
    text: SI-4(14) Information System Monitoring | Wireless Intrusion Detection
    url: SI-4(14)/
  - internal: true
    text: SI-10 Information Input Validation
    url: SI-10/
  internal: true
  text: NIST-800-53 Documentation
  url: NIST-800-53/
permalink: pretty
repos:
- description: Main repository
  name: Control Masonry
  url: https://github.com/18F/control-masonry
sass:
  style: :compressed
